name: Node.JS CI/CD

on:
  push:
    branches: [ main ]

jobs:
  
  test:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x, 24.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: use Node.JS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM install, build and test
        run:
          npm install
          npm test
        env:
          DBHOST: ${{ secrets.DBHOST }}
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}

  deploy:
    name: Deploy
    needs: [ test ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: JorgeLNJunior/render-deploy@v1.5.0
        with:
          service_id: ${{ secrets.SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}